#!/usr/bin/env node
/**
 * Rule Compiler — Reads all component YAMLs, extracts figma_rules,
 * outputs compiled-rules.json and compiled-checks.js.
 *
 * Usage: node scripts/compile-rules.js
 *
 * Both builder and checker consume the same compiled output,
 * ensuring rules cannot diverge between build and validation.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const COMPONENTS_DIR = path.join(__dirname, '..', 'docs', 'ai', 'components');
const OUTPUT_DIR = path.join(__dirname, '..', 'figma-plugin', 'builders');

// ─── 1. Read all component YAMLs ────────────────────────────────────────────

function loadAllRules() {
  const files = fs.readdirSync(COMPONENTS_DIR).filter(f => f.endsWith('.yaml'));
  const allRules = {};
  let totalRules = 0;

  for (const file of files) {
    const content = fs.readFileSync(path.join(COMPONENTS_DIR, file), 'utf8');

    // Extract figma_rules section via regex (some YAMLs have invalid syntax elsewhere)
    const rulesMatch = content.match(/^figma_rules:\n([\s\S]*?)(?=\n# ─|^\w)/m);
    if (!rulesMatch) continue;

    // Also extract component name from first line
    const nameMatch = content.match(/^component:\s*(.+)$/m);
    const componentName = nameMatch ? nameMatch[1].trim() : file.replace('.yaml', '');

    // Parse just the figma_rules section
    let doc;
    try {
      doc = yaml.load('figma_rules:\n' + rulesMatch[1]);
    } catch (e) {
      console.warn(`  ⚠ ${file}: failed to parse figma_rules section — ${e.reason}`);
      continue;
    }

    if (!doc || !doc.figma_rules || !Array.isArray(doc.figma_rules)) continue;
    allRules[componentName] = doc.figma_rules;
    totalRules += doc.figma_rules.length;

    console.log(`  ✓ ${componentName}: ${doc.figma_rules.length} rules`);
  }

  console.log(`\nTotal: ${totalRules} rules from ${Object.keys(allRules).length} components\n`);
  return allRules;
}

// ─── 2. Validate rule schema ────────────────────────────────────────────────

function validateRules(allRules) {
  const errors = [];
  const ids = new Set();

  for (const [component, rules] of Object.entries(allRules)) {
    for (const rule of rules) {
      // Required fields
      if (!rule.id) errors.push(`${component}: rule missing 'id'`);
      if (!rule.trigger) errors.push(`${component}/${rule.id}: missing 'trigger'`);
      if (!rule.condition) errors.push(`${component}/${rule.id}: missing 'condition'`);
      if (!rule.action) errors.push(`${component}/${rule.id}: missing 'action'`);
      if (!rule.check) errors.push(`${component}/${rule.id}: missing 'check'`);
      if (!rule.check?.fail_message) errors.push(`${component}/${rule.id}: missing 'check.fail_message'`);

      // Unique IDs
      if (ids.has(rule.id)) {
        errors.push(`Duplicate rule ID: ${rule.id}`);
      }
      ids.add(rule.id);

      // Valid trigger
      const validTriggers = ['after_instantiate', 'before_instantiate', 'after_append', 'after_set_property', 'after_detach'];
      if (rule.trigger && !validTriggers.includes(rule.trigger)) {
        errors.push(`${component}/${rule.id}: invalid trigger '${rule.trigger}'`);
      }

      // Valid severity
      const validSeverities = ['critical', 'error', 'warning'];
      if (rule.severity && !validSeverities.includes(rule.severity)) {
        errors.push(`${component}/${rule.id}: invalid severity '${rule.severity}'`);
      }
    }
  }

  return errors;
}

// ─── 3. Generate compiled-rules.json ────────────────────────────────────────

function generateCompiledRules(allRules) {
  const output = {};
  for (const [component, rules] of Object.entries(allRules)) {
    output[component] = rules.map(r => ({
      id: r.id,
      trigger: r.trigger,
      condition: r.condition,
      action: r.action,
      severity: r.severity || 'error',
      auto_fixable: r.auto_fixable || false,
    }));
  }
  return output;
}

// ─── 4. Generate compiled-checks.js ─────────────────────────────────────────

function generateCompiledChecks(allRules) {
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/compile-rules.js — DO NOT EDIT');
  lines.push('// Run: node scripts/compile-rules.js');
  lines.push('');
  lines.push('const COMPILED_CHECKS = {');

  for (const [component, rules] of Object.entries(allRules)) {
    lines.push(`  "${component}": [`);
    for (const rule of rules) {
      const check = rule.check;
      lines.push(`    {`);
      lines.push(`      id: "${rule.id}",`);
      lines.push(`      severity: "${rule.severity || 'error'}",`);
      lines.push(`      fail_message: ${JSON.stringify(check.fail_message)},`);
      lines.push(`      validate: ${generateValidateFunction(rule)},`);
      lines.push(`    },`);
    }
    lines.push(`  ],`);
  }

  lines.push('};');
  return lines.join('\n');
}

function generateValidateFunction(rule) {
  const check = rule.check;
  const action = rule.action;

  switch (check.assertion) {
    case 'equals':
      return generateEqualsCheck(check);
    case 'fill_matches_rgb':
      return generateFillMatchCheck(check);
    case 'fill_contrasts':
      return generateFillContrastCheck(check);
    case 'component_id_not_in':
      return generateComponentIdCheck(check);
    case 'property_is_false':
      return generatePropertyCheck(check);
    default:
      return `(node) => { /* TODO: implement ${check.assertion} */ return true; }`;
  }
}

function generateEqualsCheck(check) {
  // Parse target: "child:Checkbox.strokeAlign"
  const parts = check.target.split('.');
  const property = parts.pop();
  const selector = parts.join('.');

  if (selector.startsWith('child:')) {
    const childName = selector.replace('child:', '');
    return `(node) => {
        const child = node.findOne(n => n.name === "${childName}" && n.type === "FRAME");
        return child && child.${property} === "${check.expected}";
      }`;
  }
  return `(node) => node.${property} === "${check.expected}"`;
}

function generateFillMatchCheck(check) {
  const rgb = check.expected;
  if (Array.isArray(rgb)) {
    const t = check.tolerance || 5;
    return `(node) => {
        const target = ${getTargetSelector(check.target)};
        if (!target || !target.fills || !target.fills[0] || target.fills[0].type !== 'SOLID') return false;
        const c = target.fills[0].color;
        return Math.abs(c.r*255-${rgb[0]})<=${t} && Math.abs(c.g*255-${rgb[1]})<=${t} && Math.abs(c.b*255-${rgb[2]})<=${t};
      }`;
  }
  // If expected is "self.fills" — match to parent
  return `(node) => { /* TODO: dynamic fill match */ return true; }`;
}

function generateFillContrastCheck(check) {
  const t = check.tolerance || 10;
  return `(node) => {
      const target = ${getTargetSelector(check.target)};
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > ${t};
        }
        parent = parent.parent;
      }
      return true;
    }`;
}

function generateComponentIdCheck(check) {
  const rejectIds = JSON.stringify(check.expected);
  return `async (node) => {
      const mc = await node.getMainComponentAsync();
      const setId = mc?.parent?.id;
      return !${rejectIds}.includes(setId);
    }`;
}

function generatePropertyCheck(check) {
  const prop = check.target;
  return `(node) => {
      const props = node.componentProperties || {};
      const key = Object.keys(props).find(k => k.startsWith("${prop}"));
      return key ? props[key].value === false : true;
    }`;
}

function getTargetSelector(target) {
  if (target === 'self') return 'node';
  if (target.startsWith('child:')) {
    const name = target.replace('child:', '').split('.')[0];
    return `node.findOne(n => n.name === "${name}")`;
  }
  return 'node';
}

// ─── MAIN ───────────────────────────────────────────────────────────────────

function main() {
  console.log('🔧 Compiling DS rules from YAML...\n');

  const allRules = loadAllRules();

  // Validate
  const errors = validateRules(allRules);
  if (errors.length > 0) {
    console.error('❌ Validation errors:');
    errors.forEach(e => console.error(`  - ${e}`));
    process.exit(1);
  }
  console.log('✓ All rules valid\n');

  // Generate compiled-rules.json
  const compiledRules = generateCompiledRules(allRules);
  const rulesPath = path.join(OUTPUT_DIR, 'compiled-rules.json');
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(rulesPath, JSON.stringify(compiledRules, null, 2));
  console.log(`✓ Written: ${rulesPath}`);

  // Generate compiled-checks.js
  const checksCode = generateCompiledChecks(allRules);
  const checksPath = path.join(OUTPUT_DIR, 'compiled-checks.js');
  fs.writeFileSync(checksPath, checksCode);
  console.log(`✓ Written: ${checksPath}`);

  console.log('\n✅ Done!');
}

main();
