// AUTO-GENERATED by scripts/compile-rules.js — DO NOT EDIT
// Run: node scripts/compile-rules.js

const COMPILED_CHECKS = {
  "DSButton": [
    {
      id: "button_icon_contrast",
      severity: "critical",
      fail_message: "Dark button styles (filledB/C/outlinedLight) need light icon fills (textNeutral0_5)",
      validate: (node) => {
        const target = node.findOne(n => n.name === "Icon");
        if (!target || !target.fills || !target.fills[0] || target.fills[0].type !== 'SOLID') return false;
        const c = target.fills[0].color;
        return Math.abs(c.r*255-250)<=5 && Math.abs(c.g*255-250)<=5 && Math.abs(c.b*255-249)<=5;
      },
    },
  ],
  "DSCheckbox": [
    {
      id: "checkbox_correct_variant",
      severity: "critical",
      fail_message: "Must use small Checkbox (85:24849), not large (85:24367)",
      validate: async (node) => {
      const mc = await node.getMainComponentAsync();
      const setId = mc?.parent?.id;
      return !["85:24367"].includes(setId);
    },
    },
    {
      id: "checkbox_stroke_fix",
      severity: "critical",
      fail_message: "Checkbox strokeAlign must be INSIDE (stroke overflow fix)",
      validate: (node) => {
        const child = node.findOne(n => n.name === "Checkbox" && n.type === "FRAME");
        return child && child.strokeAlign === "INSIDE";
      },
    },
  ],
  "DSLayeredCard": [
    {
      id: "layered_content_solid_bg",
      severity: "critical",
      fail_message: "Content card MUST have a solid surfaceNeutral2 fill as its first fill — image fill goes second",
      validate: (node) => { /* TODO: dynamic fill match */ return true; },
    },
    {
      id: "layered_content_bg_before_image",
      severity: "critical",
      fail_message: "Content card first fill must be SOLID (not IMAGE) — solid bg goes before image fill",
      validate: (node) => {
        const child = node.findOne(n => n.name === "Content.fills[0]" && n.type === "FRAME");
        return child && child.type === "SOLID";
      },
    },
    {
      id: "layered_detach_before_modify",
      severity: "critical",
      fail_message: "Layered Card must be detached (detachInstance()) before adding content to child frames",
      validate: (node) => {
      const props = node.componentProperties || {};
      const key = Object.keys(props).find(k => k.startsWith("self.isComponent"));
      return key ? props[key].value === false : true;
    },
    },
  ],
  "DSListItem": [
    {
      id: "listitem_settings_leading_icon",
      severity: "critical",
      fail_message: "Settings rows MUST have a leading icon button (Neutral, Medium) — never leave Leading Item disabled",
      validate: (node) => node.value === "true",
    },
    {
      id: "listitem_card_padding_minimum",
      severity: "critical",
      fail_message: "DSCard wrapping DSListItems must have padding >= 16px (md) — NEVER use padding: 0 (causes edge-bleed)",
      validate: (node) => node.paddingLeft === ">=16",
    },
    {
      id: "listitem_no_manual_dividers",
      severity: "critical",
      fail_message: "NEVER create raw FRAME nodes as dividers — use showDivider boolean prop on DSListItem, or omit dividers entirely (HaHo default)",
      validate: (node) => node.height === "none",
    },
    {
      id: "listitem_no_spacing_between",
      severity: "error",
      fail_message: "Stack DSListItems with itemSpacing: 0 — visual separation comes from item padding + card padding, not gaps",
      validate: (node) => node.itemSpacing === "0",
    },
  ],
  "DSOverlappingCards": [
    {
      id: "overlap_text_contrast_dark",
      severity: "critical",
      fail_message: "Text on dark cards (Card-1, Card-2) must be light — use textNeutral0_5",
      validate: (node) => {
      const target = node;
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
    {
      id: "overlap_text_contrast_coral",
      severity: "critical",
      fail_message: "Text on coral card (Card-3) must be dark — use textNeutral9, NEVER white on coral",
      validate: (node) => {
      const target = node;
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
    {
      id: "overlap_text_contrast_light",
      severity: "critical",
      fail_message: "Text on light cards (Card-4, Card-5) must be dark — use textNeutral9",
      validate: (node) => {
      const target = node;
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
    {
      id: "overlap_content_at_bottom",
      severity: "critical",
      fail_message: "Card content must be pushed to bottom (primaryAxisAlignItems=MAX) to appear in the visible peek area",
      validate: (node) => {
        const child = node.findOne(n => n.name === "Card-*" && n.type === "FRAME");
        return child && child.primaryAxisAlignItems === "MAX";
      },
    },
    {
      id: "overlap_card_bg_required",
      severity: "critical",
      fail_message: "Every card MUST have a solid background fill — never clear fills after detaching",
      validate: (node) => { /* TODO: dynamic fill match */ return true; },
    },
  ],
  "DSProgressCircle": [
    {
      id: "progress_label_dark_bg",
      severity: "critical",
      fail_message: "Label text is dark on a dark parent — override labelColor to textNeutral0_5",
      validate: (node) => {
      const target = node.findOne(n => n.name === "Label");
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
    {
      id: "progress_track_dark_bg",
      severity: "critical",
      fail_message: "Track ring is invisible on dark parent — override trackColor to textNeutral0_5 at 20% opacity",
      validate: (node) => {
      const target = node.findOne(n => n.name === "Track");
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
  ],
  "DSSegmentedPicker": [
    {
      id: "picker_bg_contrast",
      severity: "critical",
      fail_message: "Picker container bg must contrast with parent card — use surfaceNeutral0_5 inside surfaceNeutral2",
      validate: (node) => {
      const target = node;
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
    {
      id: "picker_unselected_match",
      severity: "error",
      fail_message: "Unselected tab fill must match picker container bg",
      validate: (node) => { /* TODO: dynamic fill match */ return true; },
    },
    {
      id: "picker_hide_segments",
      severity: "error",
      fail_message: "Unused segments (Show 3, Show 4) must be hidden for 2-item pickers",
      validate: (node) => {
      const props = node.componentProperties || {};
      const key = Object.keys(props).find(k => k.startsWith("Show 3"));
      return key ? props[key].value === false : true;
    },
    },
  ],
  "DSTextField": [
    {
      id: "textfield_bg_contrast",
      severity: "critical",
      fail_message: "Input bg must be surfaceNeutral0_5 when inside surfaceNeutral2 card",
      validate: (node) => {
      const target = node.findOne(n => n.name === "Input");
      if (!target || !target.fills || !target.fills[0]) return true;
      let parent = target.parent;
      while (parent) {
        if (parent.fills && parent.fills[0] && parent.fills[0].type === 'SOLID') {
          const a = target.fills[0].color, b = parent.fills[0].color;
          const diff = Math.abs(a.r*255-b.r*255) + Math.abs(a.g*255-b.g*255) + Math.abs(a.b*255-b.b*255);
          return diff > 10;
        }
        parent = parent.parent;
      }
      return true;
    },
    },
  ],
};